services:
  stationeers-server:
    container_name: stationeers-server
    image: ghcr.io/thenoviceprospect/stationeers-server-ui:latest
    ports:
      - "8080:8080"
      - "27016:27016"
    volumes:
      - ./saves:/app/saves
      - ./config:/app/config
    environment:
      - STEAMCMD_DIR=/app/steamcmd
    restart: unless-stopped
    command: []
    # Add the authentication section
    # This requires your to have the GITHUB_USERNAME and GITHUB_TOKEN set in your environment
    auth:
      username: $GITHUB_USERNAME
      password: $GITHUB_TOKEN
