services:
  stationeers-server:
    container_name: stationeers-server
    image: stationeers-server-ui:latest
    build: .
    ports:
      - "8080:8080"
      - "27016:27016"
    volumes:
      - ./saves:/app/saves
      - ./config:/app/config
    environment:
      - STEAMCMD_DIR=/app/steamcmd
    restart: unless-stopped